# -*- coding: utf-8 -*-
"""show_original_image

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eZqnidJAbFQoG4c2lzof4OQuJPZEUB9N
"""

import torch
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt


#--------------
# cifar10
#--------------
# choose index
idx = 1000  # <-- set n here

# CIFAR-10 normalization (standard)
transform = transforms.Compose([
    transforms.ToTensor()
])

# load dataset
cifar10 = torchvision.datasets.CIFAR10(
    root="./data",
    train=True,
    download=True,
    transform=transform
)

# get image and label
image, label = cifar10[idx]

# CIFAR-10 class names
classes = cifar10.classes

# show image
plt.figure(figsize=(3, 3))
plt.imshow(image.permute(1, 2, 0))  # C,H,W -> H,W,C
plt.title(f"idx={idx}, label={classes[label]}")
plt.axis("off")
plt.show()


#--------------
# celebA
#--------------
# choose index
idx = 1500  # <-- set n here

# CelebA transform (resize + tensor)
transform = transforms.Compose([
    transforms.Resize((128, 128)),  # optional but recommended
    transforms.ToTensor()
])

# load CelebA dataset
celeba = torchvision.datasets.CelebA(
    root="./data",
    split="train",          # "train", "valid", or "test"
    target_type="attr",     # attributes (optional)
    download=True,
    transform=transform
)

# get image and attributes
image, attrs = celeba[idx]

# show image
plt.figure(figsize=(3, 3))
plt.imshow(image.permute(1, 2, 0))  # C,H,W -> H,W,C
plt.title(f"CelebA idx={idx}")
plt.axis("off")
plt.show()
