# -*- coding: utf-8 -*-
"""show_original_image

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eZqnidJAbFQoG4c2lzof4OQuJPZEUB9N
"""

import torch
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt

# choose index
idx = 1000  # <-- set n here

# CIFAR-10 normalization (standard)
transform = transforms.Compose([
    transforms.ToTensor()
])

# load dataset
cifar10 = torchvision.datasets.CIFAR10(
    root="./data",
    train=True,
    download=True,
    transform=transform
)

# get image and label
image, label = cifar10[idx]

# CIFAR-10 class names
classes = cifar10.classes

# show image
plt.figure(figsize=(3, 3))
plt.imshow(image.permute(1, 2, 0))  # C,H,W -> H,W,C
plt.title(f"idx={idx}, label={classes[label]}")
plt.axis("off")
plt.show()

import torch
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt

# choose index
idx = 0  # <-- set n here

# CIFAR-10 normalization (standard)
transform = transforms.Compose([
    transforms.ToTensor()
])

# load dataset
cifar10 = torchvision.datasets.CIFAR10(
    root="./data",
    train=True,
    download=True,
    transform=transform
)

# get image and label
image, label = cifar10[idx]

# CIFAR-10 class names
classes = cifar10.classes

# show image
plt.figure(figsize=(3, 3))
plt.imshow(image.permute(1, 2, 0))  # C,H,W -> H,W,C
plt.title(f"idx={idx}, label={classes[label]}")
plt.axis("off")
plt.show()